
version: "3.7"

services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:

      # timszone, ex: 'America/Toronto'
      TZ: "Europe/Berlin"

      # advertise shares, default: true, or false (open ports 137, 138)
      NMBD: "true"

      # add a single user. If you need more, use command instead of environment
      # required arg: "<username>;<passwd>"
      # <username> for user
      # <password> for user
      # [ID] for user, default: ""
      # [group] for user, default: ""
      USER: "SMB;pass"
      USER2: "mark;pass"
      USER3: "fakturama;pass"

      # set the UID for the samba share, default: ""
      USERID: "1000"

      # set the GID for the samba share, default: ""
      GROUPID: "998"

      # add a single share. If you need more, use command instead of environment
      # required arg: "<name>;</path>"
      # <share_name>;
      # <path_to_share>;
      # [browsable] default:'yes' or 'no';
      # [read_only] default:'yes' or 'no';
      # [guest]: default: 'yes' or 'no';
      # [users]: default: 'all' or list of allowed users;
      # [admins] default: 'none' or list of admin users;
      # [writelist] default: 'none' or list of users that can write to read-only share;
      # [comment] default: 'none' or description of share
      SHARE: "video;/opt/video;yes;no;no;mark,SMB;'mark';'none';'my awesome audio share"
      SHARE2: "audio;/opt/audio;yes;no;no;mark,SMB;'mark';'none';'my awesome video share"
      SHARE3: "pictures;/opt/pictures;yes;no;no;mark,SMB;'mark';'none';'my awesome picture share"
      SHARE4: "fakturama;/opt/fakturama;yes;no;no;fakturama;'mark';'none';'my awesome fakturama share"
      SHARE5: "home_mark;/opt/home_mark;yes;no;no;fakturama;'mark';'none';'my awesome home_mark share"
      SHARE6: "tv;/opt/tv;yes;no;no;mark;'mark';'none';'my awesome home_mark share"

      # workgroup/domain name for share default: "MYGROUP"
      WORKGROUP: "WORKGROUP"

      # if set, disables recycle bin for shares
      RECYCLE: ""

      # if set, disables SMB2 minimum version
      # SMB: ""

    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - smb_video:/opt/video:z # :z allows share to be used by multiple containers
      - smb_audio:/opt/audio:z # :z allows share to be used by multiple containers
      - smb_pictures:/opt/pictures:z # :z allows share to be used by multiple containers
      - smb_fakturama:/opt/fakturama:z # :z allows share to be used by multiple containers
      - smb_home_mark:/opt/home_mark:z # :z allows share to be used by multiple containers
      - smb_tv:/opt/tv:z # :z allows share to be used by multiple containers

networks:
    default:

volumes:
  smb_video:
    external: true
  smb_audio:
    external: true
  smb_pictures:
    external: true
  smb_fakturama:
    external: true
  smb_home_mark:
    external: true
  smb_tv:
    external: true
